Training AdaBoost Classifier
Traceback (most recent call last):
  File "/home/ucsp/Escritorio/Projects/OpinionMiningProject/Project/SupervisedManager.py", line 279, in <module>
    obj.trainClassifiersFirstStage()
  File "/home/ucsp/Escritorio/Projects/OpinionMiningProject/Project/SupervisedManager.py", line 140, in trainClassifiersFirstStage
    fClass = classifier.train()                                 
  File "/home/ucsp/Escritorio/Projects/OpinionMiningProject/Project/Classifier.py", line 34, in train
    return self.__trainAB()
  File "/home/ucsp/Escritorio/Projects/OpinionMiningProject/Project/Classifier.py", line 84, in __trainAB
    classifier = classifier.fit(self.__data, self.__labels)
  File "/usr/local/lib/python2.7/dist-packages/scikit_learn-0.14.1-py2.7-linux-x86_64.egg/sklearn/ensemble/weight_boosting.py", line 389, in fit
    return super(AdaBoostClassifier, self).fit(X, y, sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/scikit_learn-0.14.1-py2.7-linux-x86_64.egg/sklearn/ensemble/weight_boosting.py", line 125, in fit
    sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/scikit_learn-0.14.1-py2.7-linux-x86_64.egg/sklearn/ensemble/weight_boosting.py", line 430, in _boost
    return self._boost_discrete(iboost, X, y, sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/scikit_learn-0.14.1-py2.7-linux-x86_64.egg/sklearn/ensemble/weight_boosting.py", line 503, in _boost_discrete
    estimator.fit(X, y, sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/scikit_learn-0.14.1-py2.7-linux-x86_64.egg/sklearn/svm/base.py", line 178, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/usr/local/lib/python2.7/dist-packages/scikit_learn-0.14.1-py2.7-linux-x86_64.egg/sklearn/svm/base.py", line 233, in _dense_fit
    max_iter=self.max_iter, random_seed=random_seed)
  File "libsvm.pyx", line 220, in sklearn.svm.libsvm.fit (sklearn/svm/libsvm.c:2532)
MemoryError
